version: '3'

volumes:
  db_postgres_data: {}
  db_postgres_data_backups: {}
  db_mysql_data: {}
  db_mariadb_data: {}
  db_sqlserver_data: {}
  db_mongodb_data: {}
  db_couchdb_data: {}
  db_couchdb_config: {}
  db_cassandra_data: {}
  db_neo4j_data: {}
  pgadmindata: {}
  nginx_logs: {}
  letsencrypt_certbot: {}
  letsencrypt_logs: {}

services:
  django: &django
    image: ${CONTAINER_REGISTRY_PREFIX}/${CONTAINER_REGISTRY_REPOSITORY_NAME}:${COMPOSE_PROJECT_NAME}-${SERVICE_DJANGO_BUILD_NAME}-${SERVICE_DJANGO_BUILD_TAG_CALC}
    depends_on:
      - postgres
      - mysql
      - mariadb
      - sqlserver
      - mongodb
      - couchdb
      - cassandra
      - neo4j
      - oracle
    env_file:
      - django/.env
      - postgres/.env
    command: /uwsgi.sh
    restart: on-failure

  nginx:
    image: ${CONTAINER_REGISTRY_PREFIX}/${CONTAINER_REGISTRY_REPOSITORY_NAME}:${COMPOSE_PROJECT_NAME}-${SERVICE_NGINX_BUILD_NAME}-${SERVICE_NGINX_BUILD_TAG_CALC}
    volumes:
      - letsencrypt_certbot:/etc/letsencrypt
      - nginx_logs:/etc/nginx/logs
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
    env_file:
      - nginx/.env
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt_certbot:/etc/letsencrypt
      - letsencrypt_logs:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command: certonly --standalone --expand --non-interactive --agree-tos --email=${SERVICE_CERTBOT_EMAIL} ${SERVICE_CERTBOT_DOMAINS}

  celeryworker:
    <<: *django
    depends_on:
     - postgres
     - redis
    command: /start-celeryworker.sh
    restart: on-failure

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - redis
    command: /start-celerybeat.sh
    restart: on-failure

  flower:
    <<: *django
    ports:
    - "5555:5555"
    depends_on:
      - redis
    command: /start-flower.sh
    restart: on-failure

  postgres:
    image: postgres:11.1-alpine
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
      - db_postgres_data_backups:/backups
    ports:
      - "4000:5432"
    env_file:
      - postgres/.env

  mariadb:
    image: mariadb:10.4.0
    volumes:
      - db_mariadb_data:/var/lib/mysql
    ports:
      - "4001:3306"
    env_file:
      - mysql/.env

  mysql:
    image: mysql:5.7
    volumes:
      - db_mysql_data:/var/lib/mysql
    ports:
      - "4002:3306"
    env_file:
      - mysql/.env

  sqlserver:
    image: exoplatform/sqlserver:2017-CU8
    volumes:
      - db_sqlserver_data:/var/opt/mssql
    ports:
      - "4003:1433"
    env_file:
      - sqlserver/.env

  oracle:
    image: container-registry.oracle.com/database/standard:12.1.0.2
    # volumes:
    #   - db_oracle_data:/var/opt/mssql
    # ports:
    #   - "4003:1433"
    env_file:
      - oracle/.env

  redis:
    image: redis:3.2

  mongodb:
    image: mongo:4.0.2
    working_dir: /opt/mongodb
    env_file:
      - mongo/.env
    volumes:
      - db_mongodb_data:/opt/mongodb
    command: sh -c 'mkdir -p /opt/mongodb && mongod --port 27017 --bind_ip 0.0.0.0 --dbpath /opt/mongodb'
    ports:
      - "4004:27017"

  couchdb:
    image: couchdb:2.2.0
    env_file:
      - couchdb/.env
    volumes:
      - db_couchdb_data:/opt/couchdb/data
      - db_couchdb_config:/opt/couchdb/etc
    ports:
      - "4005:5984"

  cassandra:
    image: cassandra:2.1.20
    env_file:
      - cassandra/.env
    volumes:
      - db_cassandra_data:/var/lib/cassandra
    ports:
      - "4006:7000"

  neo4j:
    image: neo4j:3.4.9
    env_file:
      - neo4j/.env
    volumes:
      - db_neo4j_data:/data
    ports:
      - "4007:7474"

